name: tagger # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: tagger
source-code: https://github.com/NickvisionApps/Tagger
issues: https://github.com/NickvisionApps/Tagger/issues
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
layout:
  /usr/share/help:
    symlink: $SNAP/usr/share/help

parts:
  chromaprint:
    plugin: cmake
    source: https://github.com/acoustid/chromaprint.git
    source-tag: v1.5.1
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DBUILD_SHARED_LIBS=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
  tagger:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/NickvisionApps/Tagger.git
    source-branch: snap
    build-packages:
      - blueprint-compiler
      - wget
    override-pull: |
      craftctl default
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 7.0
      patch -p1 < $CRAFT_PROJECT_DIR/snap/tagger.patch
    override-build: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools:$HOME/.cargo/bin
      cd $CRAFT_PART_SRC
      dotnet tool restore
      dotnet cake --target=Publish --prefix=/snap/tagger/current/usr --ui=gnome --self-contained
      dotnet cake --target=Install --destdir=$CRAFT_PART_INSTALL
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/tagger/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    organize:
      snap/tagger/current: .
    parse-info: [ usr/share/metainfo/org.nickvision.tagger.metainfo.xml ]
apps:
  tagger:
    command: usr/bin/org.nickvision.tagger
    extensions: [gnome]
    common-id: org.nickvision.tagger
    plugs:
      - home
       - removable-media
