on:
  push:
    branches: [ "main", "snap" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: CI
permissions:
  id-token: write
  contents: read
jobs:
  flatpak:
    name: "GNOME on Flatpak"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: org.nickvision.tagger.flatpak
          manifest-path: flatpak/org.nickvision.tagger.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
          restore-cache: true
  snap:
    name: "GNOME on Snap"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft-build
        with:
          snapcraft-args: "-v"
      - uses: actions/upload-artifact@v3
        with:
          name: org.nickvision.tagger-snap-x86_64
          path: ${{ steps.snapcraft-build.outputs.snap }} 
      #- uses: diddlesnaps/snapcraft-review-action@v1
        #with:
          #snap: ${{ steps.snapcraft-build.outputs.snap }}
          #isClassic: 'false'          
      #- name: Upload and release denaro Snap
        #uses: snapcore/action-publish@v1
        #env: 
          #SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        #with:
          #snap: ${{ steps.snapcraft-build.outputs.snap }}
          #release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
