name: 🧪 Test if Tagger snap can be built on x86_64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: snapcraft-build
        
      - uses: actions/upload-artifact@v3
        with:
          name: tagger-snap
          path: ${{ steps.snapcraft-build.outputs.snap }}    
